# Required
version: 2

# Set the OS, Python version and other tools
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

# Build documentation with Sphinx
sphinx:
  configuration: docs/conf.py

# Python requirements for building docs
python:
  install:
    - requirements: docs/requirements.txt
